[package]
name = "paperless-asn-qr-codes-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
image = "0.25.6"
printpdf = { version = "0.8.2", features = ["png"] }
qrcode = "0.14.1"
qrcode-generator = "5.0.0"
